const data = {
  movies: [
    {
      _id: "101a",
      title: "Batman",
      slug: "Batman",
      image: "/image/img1.jpg",
      director: "Matt Reeves",
      state: "ongoing",
      duration: 175,
      actors: [
        "Robert Pattinson",
        "Zoe Kravitz",
        "Paul Dano",
        "Collin Farrell",
      ],
    },
    {
      _id: "102a",
      title: "Spider-Man",
      slug: "Spider-Man",
      image: "/image/img2.jpg",
      director: "Jon Watts",
      duration: 148,
      state: "ongoing",
      actors: ["Tom Holland", "Zendaya", "Paul Dano", "Collin Farrell"],
    },
    {
      _id: "103a",
      title: "Witch",
      slug: "Witch",
      image: "/image/img3.jpg",
      director: "Jon Watts",
      state: "ongoing",
      duration: 148,
      actors: ["Tom Holland", "Zendaya", "Paul Dano", "Collin Farrell"],
    },
    {
      _id: "104a",
      title: "Shin Godzilla",
      slug: "Shin Godzilla",
      image: "/image/img4.jpg",
      director: "Jon Watts",
      state: "ongoing",
      duration: 148,
      actors: ["Tom Holland", "Zendaya", "Paul Dano", "Collin Farrell"],
    },
    {
      _id: "105a",
      title: "Thor",
      slug: "Thor",
      image: "/image/img5.png",
      director: "Taika Waititi",
      state: "ongoing",
      duration: 159,
      actors: ["Chris Hemsworth", "Natalie Portman", "Tessa Thompson"],
    },
  ],
};
export default data;
